# 端口设置
server:
  port: 9090

spring:
  datasource:

    # 多数据源
    dynamic:
      #主数据源
      #设置默认的数据源或者数据源组,默认值即为master,如果你主从默认下主库的名称就是master可不定义此项。
      #primary: master
      datasource:
        master:
          url: jdbc:mysql://ximplez.com:3306/ximplezblog?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
          username: ximplezblog
          password: YZd7dXZSHzYej5Wm
          driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
        filters: stat,wall,slf4j



#mybatis-plus 插件
mybatis-plus:
  #所有的mapper映射文件
  mapper-locations:
    - classpath*:/mapper/**/*.xml
  # 实体扫描，多个package 继续往后跟
  typeAliasesPackage: com.example.demo.entiy
  # 实体扫描  BaseEntity 的子类对象
  typeAliasesSuperType: com.example.demo.entiy.User
  global-config:
    # 关闭Banner
    banner: false
    db-config:
      # 主键类型 id-type:
      # 数据库ID自增 - auto | 0   未设置主键类型 - none | 1   手动输入ID - input | 2  数字类型唯一ID - assign_id | 3  唯一ID一UUID - assign_uuid | 4
      id-type: assign_id
      logic-delete-field: valid  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
      # 更新策略 - 防止更新 null 值到数据字段中 空字符串可以更新
      # 不要改！！！如果想要非空修改 直接在对应字段上加注解 全局不允许 可空数据修改
      update-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true