name: Release Docker

# 触发条件
on:
  workflow_dispatch:
  push:
    branches:
      - 'dev/**'
      - 'release/**'
    tags:
      - 'v**'

jobs:
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 运行步骤
    steps:
    - uses: helpermethod/graalvm-native-image-toolchain@0.0.2
    - name: graalvm-native-image-toolchain
      uses: actions/setup-java@v3.0.0
      with:
        # The GraalVM version
        graalvm-version: 22.3.0
        # The Java version
        java-version: 17.0.5

    # 项目打包
    - name: Build with Maven
      run: mvn -Pnative spring-boot:build-image
